name: movie_watchlist_app
description: A Flutter movie watchlist application with OMDb API integration

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env


